version: '3.7'

services:
    provider_a:
        build:
            context: .
        image: provider_a
        container_name: aviata_a
        restart: unless-stopped
        environment:
            APP_PORT: "3000"
        command: gunicorn -b 0.0.0.0:3000 -k uvicorn.workers.UvicornWorker provider_a_main:api
    provider_b:
        build:
            context: .
        image: provider_b
        container_name: aviata_b
        restart: unless-stopped
        environment:
            APP_PORT: "8443"
        command: gunicorn -b 0.0.0.0:8443 -k uvicorn.workers.UvicornWorker provider_b_main:api