version: '3.7'

services:
    db:
        image: postgres:14.1-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=aviata_db
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        command: redis-server /usr/local/etc/redis/redis.conf

    provider_a:
        build:
            context: .
        image: provider_a
        container_name: provider_a
        restart: unless-stopped
        ports:
            - "3000:3000"
        command: gunicorn -b 0.0.0.0:3000 -k uvicorn.workers.UvicornWorker provider_a_main:api --timeout 600
    provider_b:
        build:
            context: .
        image: provider_b
        container_name: provider_b
        restart: unless-stopped
        ports:
            - "8443:8443"
        command: gunicorn -b 0.0.0.0:8443 -k uvicorn.workers.UvicornWorker provider_b_main:api --timeout 600
    airflow:
        build:
            context: .
        image: airflow
        container_name: airflow
        restart: unless-stopped
        ports:
            - "9000:9000"
        command: gunicorn -b 0.0.0.0:9000 -k uvicorn.workers.UvicornWorker airflow:api --timeout 600
        depends_on:
            - db

volumes:
    db:
        driver: local