version: '3.7'

services:
    provider_a:
        build:
            context: .
        image: provider_a
        container_name: aviata_a
        restart: unless-stopped
        environment:
            APP_PORT: "3000"
        command: gunicorn -b 0.0.0.0:3000 -k uvicorn.workers.UvicornWorker provider_a_main:api
    provider_b:
        build:
            context: .
        image: provider_b
        container_name: aviata_b
        restart: unless-stopped
        environment:
            APP_PORT: "8443"
        command: gunicorn -b 0.0.0.0:8443 -k uvicorn.workers.UvicornWorker provider_b_main:api
    airflow:
        build:
            context: .
        image: airflow
        container_name: airflow
        restart: unless-stopped
        environment:
            APP_PORT: "9000"
        command: gunicorn -b 0.0.0.0:9000 -k uvicorn.workers.UvicornWorker airflow:api

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        command: redis-server /usr/local/etc/redis/redis.conf